#! /bin/sh
pandoc -f latex -t epub -o epub/textbook.epub UniversityCoursebookAOI.tex
cd epub
unzip -o textbook.epub
cd ..
for chapter in epub/EPUB/text/*.xhtml
do
echo converting ${chapter}...
pandoc -f html -t markdown -o ${chapter/xhtml/md} ${chapter}
done
cp epub/EPUB/text/*.md docs/_book
cp epub/EPUB/media/* docs/media
