#! /bin/sh
pandoc -f latex -t epub -o epub/textbook.epub UniversityCoursebookAOI.tex
unzip epub/textbook.epub
cp -r epub/media docs
for chapter in epub/text/*.xhtml
do
pandoc -f html -t gfm -o ${${chapter/xhtml/md}/text/../docs} book/${chapter}
done
